app/application/views/auth.py
from flask import Blueprint, app, flash, redirect, render_template, request, url_for
from flask_login import LoginManager, current_user
from sqlalchemy import and_
from werkzeug.security import generate_password_hash, check_password_hash
from ..models.models import TaskList, User, db
from ..objects.forms import Login, Register
from ..objects.helpers import generate_list_id


# Blueprint config
auth = Blueprint(
    "auth", __name__, template_folder="templates", url_prefix="/users"
)

# Create manager instance + user loader
login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    return db.get_or_404(User, user_id)


@auth.route("/register", methods=["GET", "POST"])
def register_user():
    registerform = Register()
    if registerform.validate_on_submit():
        check_exist = db.session.execute(
            db.select(User).where(
                and_(
                    User.email == registerform.email.data,
                    User.username == registerform.username.data,
                )
            )
        )

        if check_exist is None:
            # create new user var
            hashed_password = generate_password_hash(registerform.password.data)
            new_user = User(
                username=registerform.username.data,
                email=registerform.email.data,
                password=hashed_password
            )
            # Retrieve current anonymous tasklist or generate new tasklist 
            tasks = db.session.execute(db.select(TaskList).where(TaskList.listId == request.args.get("tasklist"))).scalar()
            if tasks is None:
                list_id = generate_list_id()
                # Removed retry generate loop for now
                tasks = TaskList(
                    listId=list_id
                )
            tasks.author = new_user
            new_user.tasklist = tasks
            db.session.add(tasks)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for("show_list", list_id=tasks.listId))
        else:
            flash("Username or email has already been taken, please try another username or email")
            return render_template("register.html", form=registerform, current_user=current_user)
    elif registerform.errors:
        return render_template("register.html", form=registerform, errors=registerform.errors, current_user=current_user)
    return render_template("register.html", form=registerform, current_user=current_user)


@auth.route("/verify", methods=["GET"])
def verify_user():
    pass


@auth.route("/login", methods=["GET", "POST"])
def login_user():
    loginform = Login()

    if loginform.validate_on_submit():
        retrieved_user = db.session.execute(
            db.select(User).where(User.email == loginform.email.data)
        ).scalar()
        if retrieved_user is None:
            flash("User does not exist, please make a new account")
            return render_template("login.html", form=loginform)
        if check_password_hash(retrieved_user.password, loginform.password.data):
            flash("Email and password do not match")
            return render_template("login.html", form=loginform)
        else:
            login_user(retrieved_user)
            return redirect(url_for("tasklist.show_list", list_id=current_user.tasklist.listId))
    elif loginform.errors:
        return render_template("login.html", errors=loginform.errors, form=loginform)
    return render_template("login.thml", form=loginform)


@auth.route("logout")
def logout_user():
    logout_user()
    return redirect(url_for("tasklist.home_page"))

app/application/templates/footer.html
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Cafes and Code 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        {{ bootstrap.load_js() }}
        <!-- Custom js/jquery -->
        <script type="text/javascript">
            $(document).ready(function(){
                console.log($(".check-state"))
                $(".check-state").change(function(event){
                    console.log("here")
                });
            });
        </script>
    </body>
  </html>

app/application/templates/header.html
<!DOCTYPE html>
<html lang="en-us">
    
    <head>
        <title>To-Do List</title>
        <meta charset="UTF-8">
        {{ bootstrap.load_css() }}
        <link rel="stylesheet" href="assets/css/styles.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    </head>
    <body>
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 px-3 mb-4 border-bottom">
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                    <span class="fs-4">To-Do list</span>
                </a>
            </div>

            <div class="col-md-3 text-end">
                {% if not current_user.is_authenticated %}
                    <a href="{{ url_for('auth.login_user') }}" class="btn btn-primary">Login</a>
                    {% if current_user.tasklist is not none %}
                    <a href="{{ url_for('auth.register_user') }}" class="btn btn-primary">Register</a>
                    {% else %}
                    <a href="{{ url_for('auth.register_user', tasklist=tasks.listId) }}" class="btn btn-primary">Register</a>
                    {% endif %}
                {% endif %}

                {% if current_user.is_authenticated %}
                    <span>Hello {{current_user.username}}!</p>
                    <a href="{{ url_for('auth.logout_user') }}" class="btn btn-primary">Logout</a>
                {% endif %}
            </div>
        </header>

app/application/templates/login.html
{% include "header.html" %}
{% from 'bootstrap5/form.html' import render_form %}
<div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
    <main class="form-signin w-50 m-auto justify-content-center">
        {% with messages = get_flashed_messages() %}
        <p class="flash text-danger">{{ messages[0] }}</p>
        {% endwith %}
        <form action="{{ url_for('auth.login_user') }}" method="post">
            {{ form.csrf_token }}
            <h1 class="h3 mb-3 fw-normal">Login</h1>

            <div class="form-floating">
                {{ form.email(class="form-control", placeholder="") }}
                {{ form.email.label(for="email") }}
            </div>
            <div class="form-floating">
                {{ form.password(class="form-control", placeholder="")}}
                {{ form.password.label(for="password") }}
            </div>

            {{ form.submit(class="btn btn-primary w-100 py-2") }}
        </form>
    </main>
</div>
{% include "footer.html" %}

app/application/templates/register.html
{% include "header.html" %}
{% from 'bootstrap5/form.html' import render_form %}
<div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
    <main class="form-signin w-50 m-auto">
        {% with messages = get_flashed_messages() %}
            <p class="flash text-danger">{{ messages[0] }}</p>
        {% endwith %}
        <form class="needs-validation" novalidate action="{{ url_for('auth.register_user') }}" method="post">
            {{ form.csrf_token }}
            <h1 class="h3 mb-3 fw-normal">Register</h1>

            <div class="form-floating">
                {{ form.username(class="form-control", placeholder="") }}
                {{ form.username.label(for="username") }}
            </div>
            <div class="form-floating">
                {{ form.email(class="form-control", placeholder="") }}
                {{ form.email.label(for="email") }}
            </div>
            <div class="form-floating">
                {{ form.password(class="form-control", placeholder="") }}
                {{ form.password.label(for="password") }}
            </div>
            <div class="form-floating">
                {{ form.repeat_pw(class="form-control", placeholder="") }}
                {{ form.repeat_pw.label(for="repeat_pw") }}
            </div>

            {{ form.submit(class="btn btn-primary w-100 py-2") }}
        </form>
    </main>
</div>
{% include "footer.html" %}